### PR TITLE
emptyset symbol in LaTeX

### LINKED ISSUE #213: `\emptyset` cannot be generated in Latex mode
Plurimath cannot generate `\emptyset` in Latex mode.

image

Using `\varnothing` could be an alternative, but I believe `\emptyset` is not deprecated and should be producible.

### PR DESCRIPTION
**Pull request by suleman-uzair**
This PR adds `emptyset` symbol in LaTex and updates the **`LaTeX`** supported symbols list.

closes #213

### CODE REVIEW

**Review by anermina — APPROVED** [review]

**Review by HassanAkbar — APPROVED** [review]
LGTM 👍

**Comment by ronaldtse** [comment]
@suleman-uzair : how can I use `emptyset` in other math languages like asciimath? We want to implement support for all of them.

**Review by ronaldtse — CHANGES_REQUESTED** [review]
This concept needs to be accessible via all math languages.

**Comment by ronaldtse** [comment]
Thank you @anermina for the clarification!

@suleman-uzair do we have the empty set concept in the Math class?

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@suleman-uzair please merge when ready. Thanks!

**Pull request merged**
