### PR TITLE
Updated encoding from named to hexadecimal

### LINKED ISSUE #183: Never ever use HTML escapes in plurimath
`&nsbp;` is understood fine in HTML. But Metanorma is not HTML, it is XML. And in XML, escapes like that are not understood at all without special processing. 

Please replace all named escapes in Plurimath output (other than `&gt; &lt; &amp;`) with hexadecimal escapes; e.g. `&#xa0;` not `&nbsp;`

### PR DESCRIPTION
**Pull request by suleman-uzair**
This PR changes the encoding of Unicode from named to hexadecimal.

closes #183

### CODE REVIEW

**Comment by suleman-uzair** [comment]
@opoudjis With the latest changes, these `&gt; &lt; &amp;` will also convert to hexadecimal, Is this acceptable or should I revert these tags?

**Comment by opoudjis** [comment]
> @opoudjis With the latest changes, these `&gt; &lt; &amp;` will also convert to hexadecimal, Is this acceptable or should I revert these tags?

Acceptable.

**Review by opoudjis — APPROVED** [review]

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
@suleman-uzair can you please help release? Thanks.

**Comment by suleman-uzair** [comment]
@opoudjis, @ronaldtse I have released a new version 0.4.3.

**Pull request merged**
