### PR TITLE
use BigDecimal for digit_count: https://github.com/plurimath/plurimat…

### PR DESCRIPTION
**Pull request by opoudjis**
…h/issues/262

### CODE REVIEW

**Comment by suleman-uzair** [comment]
@opoudjis will release the version as soon as checks pass.

**Review by suleman-uzair — APPROVED** [review]

**Comment by suleman-uzair** [comment]
@opoudjis just released version **0.8.9**.

**Comment by opoudjis** [comment]
Thank you!

**Comment by ronaldtse** [comment]
@suleman-uzair Plurimath is also compiled to JS through Opal. Does Opal provide BigDecimal? If not we need to do a switch during compilation.

ping @hmdne

**Comment by suleman-uzair** [comment]
> Does Opal provide BigDecimal? 

@ronaldtse Yes, It is mentioned in the documentation [here](https://opalrb.com/docs/api/v1.8.1/stdlib/BigDecimal.html) that **Opal** supports **BigDecimal**, So I think it should work.

**Comment by ronaldtse** [comment]
That is awesome, thanks!

**Pull request merged**
