### PR TITLE
All symbols support in all languages

### LINKED ISSUE #229: Better mechanism to manage and list out supported symbols
Instead of having these files:
* https://github.com/plurimath/plurimath/blob/main/Latex-Supported-Data.adoc
* https://github.com/plurimath/plurimath/blob/main/AsciiMath-Supported-Data.adoc
* https://github.com/plurimath/plurimath/blob/main/MathML-Supported-Data.adoc
* https://github.com/plurimath/plurimath/pull/234/files#diff-10e44a82d0fc52ed660b3d0d06a3817b059831e2aef8bb143a385a5afd046611

I'd rather they are in a single YAML file or generated from a Ruby call to list out classes.

We should not need to manually keep these files.

### PR DESCRIPTION
**Pull request by suleman-uzair**
This PR
1. Adds new files/classes for each symbol and parenthesis.
2. Adds wrapper `__{symbol_name}` support for inter-lingual symbols support
  a. for example, **backepsilon** is supported in **LaTeX** and not support in **AsciiMath**, but now, we can use it using `__{backepsilon}` syntax.
3. Adds specs for each symbol and parenthesis.

closes #229

### CODE REVIEW

**Comment by suleman-uzair** [comment]
@opoudjis, Adding classes or files for all symbols represents a structural change. While I’ve made every effort to update all scenarios, it’s prudent to test before merging or releasing a new version, just to be safe.

**Comment by opoudjis** [comment]
I am in hell because of ISO-10303-SRL, @suleman-uzair, which is taking me out of action for the next two weeks, so you are going to have to be more helpful here. What kind of testing or review are you expecting of me?

If this is about seeing if it blows up any Metanorma documents, then the testing needs to be between you and @CAMOBAP. I have little idea how Github Actions works for this kind of testing, and I don't have the spare time to work it out.

* @CAMOBAP Please run metanorma-cli on Github Actions with a Gemfile.devel pointing to this branch of plurimath. @CAMOBAP I don't know if you got Gemfile.devel working on metanorma-cli. Please do so if you haven't already, and do a run with this branch, so we can confirm that it does not introduce any new crashes.
* Please show @suleman-uzair how to do so himself in future, because as an infrastructure gem, he will need to run sanity checks on plurimath rather than me finding out on release about plurimath bugs. This has happened a couple of times already. What is involved @suleman-uzair is you pushing a PR to metanorma-cli, with a Gemfile.devel file at top level looking like this:

````
gem "plurimath", git: "https://github.com/plurimath/plurimath", branch: "whatever"
````


But like I said, I have no idea if this is working for metanorma-cli yet; I know we tried to get it working, but I don't remember if we succeeded.

That aside, find a Metanorma document with backepsilon in it, and compile it.

**Comment by ronaldtse** [comment]
I can confirm that `__{backepsilon}` only works sometimes in AsciiMath:

## Works

```ruby
Plurimath::Math.parse("__{backepsilon}", :asciimath).to_mathml
=> "<math xmlns=\"http://www.w3.org/1998/Math/MathML\" display=\"block\">\n  <mstyle displaystyle=\"true\">\n    <mi>&#x3f6;</mi>\n  </mstyle>\n</math>\n"
```

## Fails

```ruby
irb(main):014:0> string = "[u_0, u_1, u_2, u_3, ... , u_n] __{backepsilon} [[0 leq u_i leq 1] wedge sum u_i = 1.0]"
=> "[u_0, u_1, u_2, u_3, ... , u_n] __{backepsilon} [[0 leq u_i leq 1] wedge sum u_i = 1.0]"
irb(main):015:0> puts Plurimath::Math.parse(string, :asciimath).to_mathml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mstyle displaystyle="true">                                                            
    <msub>                                                             
      <mrow>                                                           
        <mo>[</mo>                                                     
        <msub>                                                         
          <mi>u</mi>                                                   
          <mn>0</mn>
        </msub>
        <mo>,</mo>
        <msub>
          <mi>u</mi>
          <mn>1</mn>
        </msub>
        <mo>,</mo>
        <msub>
          <mi>u</mi>
          <mn>2</mn>
        </msub>
        <mo>,</mo>
        <msub>
          <mi>u</mi>
          <mn>3</mn>
        </msub>
        <mo>,</mo>
        <mo>&#x2026;</mo>
        <mo>,</mo>
        <msub>
          <mi>u</mi>
          <mi>n</mi>
        </msub>
        <mo>]</mo>
      </mrow>
      <mo>_</mo>
    </msub>
    <mrow>
      <mo>{</mo>
      <mi>b</mi>
      <mi>a</mi>
      <mi>c</mi>
      <mi>k</mi>
      <mi>&#x3b5;</mi>
      <mo>}</mo>
    </mrow>
    <mrow>
      <mo>[</mo>
      <mrow>
        <mo>[</mo>
        <mn>0</mn>
        <mo>&#x2264;</mo>
        <mi>q</mi>
        <msub>
          <mi>u</mi>
          <mi>i</mi>
        </msub>
        <mo>&#x2264;</mo>
        <mi>q</mi>
        <mn>1</mn>
        <mo>]</mo>
      </mrow>
      <mo>&#x2227;</mo>
      <mo>&#x2211;</mo>
      <msub>
        <mi>u</mi>
        <mi>i</mi>
      </msub>
      <mo>=</mo>
      <mn>1.0</mn>
      <mo>]</mo>
    </mrow>
  </mstyle>
</math>
```
Screenshot 2024-05-20 at 8 29 08 PM

Another example breaks Plurimath as well:
* https://github.com/plurimath/plurimath/issues/250

**Comment by suleman-uzair** [comment]
@ronaldtse, looking into it right now.

**Comment by opoudjis** [comment]
@suleman-uzair see https://github.com/plurimath/plurimath/issues/249 for two formulas in the BIPM samples that the PR testing has identified as breaking.

**Comment by opoudjis** [comment]
Btw, this testing of metanorma-cli that @CAMOBAP has set up in that ticket means you won't need to extract all formulas from mn-samples-* for testing (and we are likely to keep adding documents anyway). You should have a large testbed of formulas for Plurimath testing, but you can dynamically test against our collections of documents this way anyway.

**Comment by ronaldtse** [comment]
@suleman-uzair I'm worried that we have too many files. A number of symbols don't "really" need to be in separate files?

But I guess we can merge this first and then simplify. Thanks.

**Pull request merged**
